echo '***************************************************************'
echo '* Qalá.js v0.8.4 - Secure Token-Based Access Control Library  *'
echo '***************************************************************'
echo '* Thank you for installing Qalá.js!                           *'
echo '* A discrete and secure environment variables keeper.         *'
echo '*                                                             *'
echo '* Features:                                                   *'
echo '*   • 🔐 Encrypted storage (AES-256-GCM, ECC key exchange)    *'
echo '*   • 🔑 JWT-based authentication with secure token refresh   *'
echo '*   • 🚀 Multiple modes: Standalone, Integrated, or ENV       *'
echo '*   • 🛡️ IP verification & encrypted backups                  *'
echo '*                                                             *'
echo '* Usage Modes:                                                *'
echo '*   • Standalone: Runs as an independent secure secrets API   *'
echo '*   • Integrated: Embedded into an Express app                *'
echo '*   • ENV Mode: Zero-config access via process.env            *'
echo '*                                                             *'
echo '* Docs & Support:                                             *'
echo '*   📖 https://github.com/Qala-Security/qala.js               *'
echo '*   🛠 Report issues: GitHub Issues Page                      *'
echo '***************************************************************'
