console.log('***************************************************************');
console.log('* Qalá.js v0.8.7 - Secure Token-Based Access Control Library  *');
console.log('***************************************************************');
console.log('* Thank you for installing Qalá.js!                           *');
console.log('* A discrete and secure environment variables keeper.         *');
console.log('*                                                             *');
console.log('* Features:                                                   *');
console.log('*   • 🔐 Encrypted storage (AES-256-GCM, ECC key exchange)    *');
console.log('*   • 🔑 JWT-based authentication with secure token refresh   *');
console.log('*   • 🚀 Multiple modes: Standalone, Integrated, or ENV       *');
console.log('*   • 🛡️ IP verification & encrypted backups                  *');
console.log('*                                                             *');
console.log('* Usage Modes:                                                *');
console.log('*   • Standalone: Runs as an independent secure secrets API   *');
console.log('*   • Integrated: Embedded into an Express app                *');
console.log('*   • ENV Mode: Zero-config access via process.env            *');
console.log('*                                                             *');
console.log('* Docs & Support:                                             *');
console.log('*   📖 https://github.com/Qala-Security/qala.js               *');
console.log('*   🛠 Report issues: GitHub Issues Page                      *');
console.log('***************************************************************');
